name = "brightbound-adventures"
main = "worker.js"
compatibility_date = "2024-01-01"

[site]
bucket = "./"

# Custom domain configuration
# routes = [
#   { pattern = "brightbound.matthurley.dev", custom_domain = true }
# ]

# For development
[env.dev]
name = "brightbound-adventures-dev"
