name = "brightbound-adventures"
pages_build_output_dir = "./"
compatibility_date = "2024-01-15"

[env.production]
name = "brightbound-adventures"

[env.preview]
name = "brightbound-adventures-preview"
